import type { Metadata } from "next";

import "./globals.css";
import NavBar from "@/components/rootLayout/NavBar";
import Footer from "@/components/rootLayout/footer/Footer";

export const metadata: Metadata = {
  title: "Aty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
